sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: nvQ/bgaw8MCZVTYK3SiCam/p0kU0z5/ez0ZCGOW5Bg6iCsuFVeMCw+WQ69LdupqtU3LR9PdI3L591/2aJATgbpufWo7YY4ByCjXVjL5pWxYTje5kPOpnfo/l0hNlVY5ZJuGxJzGeXiEmpFXV9DkBl62fosMD3h1ld8LqfwYL1cA=
  email:
    recipients:
      secure: ksG18Qe2dXjOaYMedwKSG9HuShlrbdxGKclI/dK6/OETwRUNb/cAnmEBG1jHMA41VHYDCEQvXTuJyGvibKMI5IfVOc3+FgbjZFKT1PODLdx4V2lCq0C4dWY6NvMnDpvHzcjJBdDcY2JM3Hr//4pCBeelTIeggm7XcDlYpxVOpmk=
